on:
  workflow_dispatch:
jobs:
  package:
    name: "Package zip"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir package
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install --target ./package -r requireents.txt
      - run: zip -r my_package.zip ./package
      - run: zip my_package.zip app.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package.zip
          path: my_package.zip
